package com.besson.endfield.item;

import com.besson.endfield.ArknightsEndfield;
import com.besson.endfield.block.ModBlocks;
import com.besson.endfield.item.custom.PortableOriginiumRigItem;
import com.besson.endfield.item.custom.ProtocolAnchorCoreItem;
import com.besson.endfield.item.custom.ThermalBankItem;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.Rarity;
import net.minecraft.world.level.block.Block;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.fml.DeferredWorkQueue;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

import java.util.function.Supplier;

public class ModItems {
    public static final DeferredRegister<Item> ITEMS =
            DeferredRegister.create(ForgeRegistries.ITEMS, ArknightsEndfield.MOD_ID);

    public static final RegistryObject<Item> PORTABLE_ORIGINIUM_RIG_ITEM = ITEMS.register("portable_originium_rig",
            () -> new PortableOriginiumRigItem(ModBlocks.PORTABLE_ORIGINIUM_RIG.get(), new Item.Properties()));
    public static final RegistryObject<Item> PROTOCOL_ANCHOR_CORE_ITEM = ITEMS.register("protocol_anchor_core",
            () -> new ProtocolAnchorCoreItem(ModBlocks.PROTOCOL_ANCHOR_CORE.get(), new Item.Properties().rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> THERMAL_BANK_ITEM = ITEMS.register("thermal_bank",
            () -> new ThermalBankItem(ModBlocks.THERMAL_BANK.get(), new Item.Properties().rarity(Rarity.UNCOMMON)));

    public static final RegistryObject<Item> AGGAGRIT = ITEMS.register("aggagrit", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> AGGAGRIT_BLOCK = ITEMS.register("aggagrit_block", () -> new Item(new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> AGGAGRIT_CLUSTER = ITEMS.register("aggagrit_cluster", () -> new Item(new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> AKETINE = ITEMS.register("aketine", () -> new BlockItem(ModBlocks.AKETINE_BLOCK.get(), new Item.Properties()));
    public static final RegistryObject<Item> AKETINE_POWDER = ITEMS.register("aketine_powder", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> AKETINE_SEED = ITEMS.register("aketine_seed", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> AMBER_RICE = ITEMS.register("amber_rice", () -> new BlockItem(ModBlocks.AMBER_RICE_BLOCK.get(), new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> AMBER_RICE_SEED = ITEMS.register("amber_rice_seed", () -> new Item(new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> AMETHYST_BOTTLE = ITEMS.register("amethyst_bottle", () -> new Item(new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> AMETHYST_COMPONENT = ITEMS.register("amethyst_component", () -> new Item(new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> AMETHYST_FIBER = ITEMS.register("amethyst_fiber", () -> new Item(new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> AMETHYST_ORE = ITEMS.register("amethyst_ore", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> AMETHYST_PART = ITEMS.register("amethyst_part", () -> new Item(new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> AMETHYST_POWDER = ITEMS.register("amethyst_powder", () -> new Item(new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> ARTS_TUBE = ITEMS.register("arts_tube", () -> new Item(new Item.Properties().rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> ARTS_VIAL = ITEMS.register("arts_vial", () -> new Item(new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> ASHPIN_REMEDY = ITEMS.register("ashpin_remedy", () -> new Item(new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> BIZARROTACK = ITEMS.register("bizarrotack", () -> new Item(new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> BIZARRO_CHILI = ITEMS.register("bizarro_chili", () -> new Item(new Item.Properties().rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> BLANCHED_REMEDY = ITEMS.register("blanched_remedy", () -> new Item(new Item.Properties().rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> BUCKFLOWER = ITEMS.register("buckflower", () -> new BlockItem(ModBlocks.BUCKFLOWER_BLOCK.get(), new Item.Properties()));
    public static final RegistryObject<Item> BUCKFLOWER_POWDER = ITEMS.register("buckflower_powder", () -> new Item(new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> BUCKFLOWER_SEED = ITEMS.register("buckflower_seed", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> BUCKPILL_L = ITEMS.register("buckpill_l", () -> new Item(new Item.Properties().rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> BUCKPILL_RF = ITEMS.register("buckpill_rf", () -> new ModEpicItem(new Item.Properties()));
    public static final RegistryObject<Item> BUCKPILL_S = ITEMS.register("buckpill_s", () -> new Item(new Item.Properties().rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> BUCK_CAPSULE_A = ITEMS.register("buck_capsule_a", () -> new Item(new Item.Properties().rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> BUCK_CAPSULE_B = ITEMS.register("buck_capsule_b", () -> new Item(new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> BUCK_CAPSULE_C = ITEMS.register("buck_capsule_c", () -> new Item(new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> BUGTACK = ITEMS.register("bugtack", () -> new Item(new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> CANNED_CITROME_A = ITEMS.register("canned_citrome_a", () -> new Item(new Item.Properties().rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> CANNED_CITROME_B = ITEMS.register("canned_citrome_b", () -> new Item(new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> CANNED_CITROME_C = ITEMS.register("canned_citrome_c", () -> new Item(new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> CARBON = ITEMS.register("carbon", () -> new Item(new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> CARBON_POWDER = ITEMS.register("carbon_powder", () -> new Item(new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> CARTILAGE_BIT = ITEMS.register("cartilage_bit", () -> new Item(new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> CARTILAGE_TACK = ITEMS.register("cartilage_tack", () -> new Item(new Item.Properties().rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> CHITIN_BIT = ITEMS.register("chitin_bit", () -> new Item(new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> CITROBUCKY_MIX = ITEMS.register("citrobucky_mix", () -> new Item(new Item.Properties().rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> CITROME = ITEMS.register("citrome", () -> new BlockItem(ModBlocks.CITROME_BLOCK.get(), new Item.Properties()));
    public static final RegistryObject<Item> CITROME_JAM = ITEMS.register("citrome_jam", () -> new Item(new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> CITROME_JELLY = ITEMS.register("citrome_jelly", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> CITROME_POWDER = ITEMS.register("citrome_powder", () -> new Item(new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> CITROME_PUDDING = ITEMS.register("citrome_pudding", () -> new Item(new Item.Properties().rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> CITROME_SEED = ITEMS.register("citrome_seed", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> CITROMIX = ITEMS.register("citromix", () -> new Item(new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> CITROMIX_L = ITEMS.register("citromix_l", () -> new Item(new Item.Properties().rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> CITROMIX_RF = ITEMS.register("citromix_rf", () -> new ModEpicItem(new Item.Properties()));
    public static final RegistryObject<Item> CITROMIX_S = ITEMS.register("citromix_ss", () -> new Item(new Item.Properties().rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> COARSE_FLATBREAD = ITEMS.register("coarse_flatbread", () -> new Item(new Item.Properties().rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> CORRECTIVE_REMEDY = ITEMS.register("corrective_remedy", () -> new ModEpicItem(new Item.Properties()));
    public static final RegistryObject<Item> CRYSTON_BOTTLE = ITEMS.register("cryston_bottle", () -> new Item(new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> CRYSTON_COMPONENT = ITEMS.register("cryston_component", () -> new Item(new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> CRYSTON_FIBER = ITEMS.register("cryston_fiber", () -> new Item(new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> CRYSTON_PART = ITEMS.register("cryston_part", () -> new Item(new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> CRYSTON_POWDER = ITEMS.register("cryston_powder", () -> new Item(new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> CUPRIUM = ITEMS.register("cuprium", () -> new Item(new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> CUPRIUM_COMPONENT = ITEMS.register("cuprium_component", () -> new Item(new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> CUPRIUM_JAR = ITEMS.register("cuprium_jar", () -> new Item(new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> CUPRIUM_ORE = ITEMS.register("cuprium_ore", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> CUPRIUM_PART = ITEMS.register("cuprium_part", () -> new Item(new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> CUPRIUM_POWDER = ITEMS.register("cuprium_powder", () -> new Item(new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> DENSE_CARBON_POWDER = ITEMS.register("dense_carbon_powder", () -> new Item(new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> DENSE_FERRIUM_POWDER = ITEMS.register("dense_ferrium_powder", () -> new Item(new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> DENSE_ORIGINIUM_POWDER = ITEMS.register("dense_originium_powder", () -> new Item(new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> DENSE_ORIGOCRUST_POWDER = ITEMS.register("dense_origocrust_powder", () -> new Item(new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> FERRIUM = ITEMS.register("ferrium", () -> new Item(new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> FERRIUM_BOTTLE = ITEMS.register("ferrium_bottle", () -> new Item(new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> FERRIUM_COMPONENT = ITEMS.register("ferrium_component", () -> new Item(new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> FERRIUM_ORE = ITEMS.register("ferrium_ore", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> FERRIUM_PART = ITEMS.register("ferrium_part", () -> new Item(new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> FERRIUM_POWDER = ITEMS.register("ferrium_powder", () -> new Item(new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> FILLET = ITEMS.register("fillet", () -> new Item(new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> FILLET_CONFIT = ITEMS.register("fillet_confit", () -> new Item(new Item.Properties().rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> FIREBUCKLE = ITEMS.register("firebuckle", () -> new BlockItem(ModBlocks.FIREBUCKLE_BLOCK.get(), new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> FIREBUCKLE_POWDER = ITEMS.register("firebuckle_powder", () -> new Item(new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> FIRESTOVE_RICE = ITEMS.register("firestove_rice", () -> new Item(new Item.Properties().rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> FIRETACK = ITEMS.register("firetack", () -> new Item(new Item.Properties().rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> FLUFFED_JINCAO = ITEMS.register("fluffed_jincao", () -> new BlockItem(ModBlocks.FLUFFED_JINCAO_BLOCK.get(), new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> FLUFFED_JINCAO_POWDER = ITEMS.register("fluffed_jincao_powder", () -> new Item(new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> FORTIFYING_INFUSION = ITEMS.register("fortifying_infusion", () -> new Item(new Item.Properties().rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> GARDEN_FRIED_RICE = ITEMS.register("garden_fried_rice", () -> new Item(new Item.Properties().rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> GARDEN_STIR_FRY = ITEMS.register("garden_stir_fry", () -> new Item(new Item.Properties().rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> GINSENG_MEAT_STEW = ITEMS.register("ginseng_meat_stew", () -> new ModEpicItem(new Item.Properties()));
    public static final RegistryObject<Item> GLOWBUG = ITEMS.register("glowbug", () -> new Item(new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> GRASS_CHAFF = ITEMS.register("grass_chaff", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> GROUND_BUCKFLOWER_POWDER = ITEMS.register("ground_buckflower_powder", () -> new Item(new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> GROUND_CITROME_POWDER = ITEMS.register("ground_citrome_powder", () -> new Item(new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> HC_BATTERY = ITEMS.register("hc_battery", () -> new Item(new Item.Properties().rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> HOLLOW_BONE = ITEMS.register("hollow_bone", () -> new Item(new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> HOLLOW_BONECHIP = ITEMS.register("hollow_bonechip", () -> new Item(new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> HOT_CRUNCHY_RIBS = ITEMS.register("hot_crunchy_ribs", () -> new ModEpicItem(new Item.Properties()));
    public static final RegistryObject<Item> INDUSTRIAL_EXPLOSIVE = ITEMS.register("industrial_explosive", () -> new Item(new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> JINCAO = ITEMS.register("jincao", () -> new BlockItem(ModBlocks.JINCAO_BLOCK.get(), new Item.Properties()));
    public static final RegistryObject<Item> JINCAO_DRINK = ITEMS.register("jincao_drink", () -> new Item(new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> JINCAO_INFUSION = ITEMS.register("jincao_infusion", () -> new ModEpicItem(new Item.Properties()));
    public static final RegistryObject<Item> JINCAO_POWDER = ITEMS.register("jincao_powder", () -> new Item(new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> JINCAO_SEED = ITEMS.register("jincao_seed", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> JINCAO_TEA = ITEMS.register("jincao_tea", () -> new Item(new Item.Properties().rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> JINCAO_TISANE = ITEMS.register("jincao_tisane", () -> new Item(new Item.Properties().rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> KUNST_TUBE = ITEMS.register("kunst_tube", () -> new Item(new Item.Properties().rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> KUNST_VIAL = ITEMS.register("kunst_vial", () -> new Item(new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> LC_BATTERY = ITEMS.register("lc_battery", () -> new Item(new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> MEAT_STIR_FRY = ITEMS.register("meat_stir_fry", () -> new ModEpicItem(new Item.Properties()));
    public static final RegistryObject<Item> MOSSFIELD_PIE = ITEMS.register("mossfield_pie", () -> new ModEpicItem(new Item.Properties()));
    public static final RegistryObject<Item> ORIGINIUM_ORE = ITEMS.register("originium_ore", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> ORIGINIUM_POWDER = ITEMS.register("originium_powder", () -> new Item(new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> ORIGOCRUST = ITEMS.register("origocrust", () -> new Item(new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> ORIGOCRUST_POWDER = ITEMS.register("origocrust_powder", () -> new Item(new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> PACKED_ORIGOCRUST = ITEMS.register("packed_origocrust", () -> new Item(new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> PERPLEXING_MEDICATION = ITEMS.register("perplexing_medication", () -> new Item(new Item.Properties().rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> PRESERVE_STEW = ITEMS.register("preserve_stew", () -> new Item(new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> REDJADE_GINSENG = ITEMS.register("redjade_ginseng", () -> new BlockItem(ModBlocks.REDJADE_GINSENG_BLOCK.get(), new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> REDJADE_GINSENG_SEED = ITEMS.register("redjade_ginseng_seed", () -> new Item(new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> REED_RYE = ITEMS.register("reed_rye", () -> new BlockItem(ModBlocks.REED_RYE_BLOCK.get(), new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> REED_RYE_SEED = ITEMS.register("reed_rye_seed", () -> new Item(new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> SANDLEAF = ITEMS.register("sandleaf", () -> new BlockItem(ModBlocks.SANDLEAF_BLOCK.get(), new Item.Properties()));
    public static final RegistryObject<Item> SANDLEAF_POWDER = ITEMS.register("sandleaf_powder", () -> new Item(new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> SANDLEAF_SEED = ITEMS.register("sandleaf_seed", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> SAVORY_FILLET = ITEMS.register("savory_fillet", () -> new Item(new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> SAVORY_TANGBAO = ITEMS.register("savory_tangbao", () -> new ModEpicItem(new Item.Properties()));
    public static final RegistryObject<Item> SAVORY_TANGMIAN = ITEMS.register("savory_tangmian", () -> new Item(new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> SCORCHBUG = ITEMS.register("scorchbug", () -> new Item(new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> SC_BATTERY = ITEMS.register("sc_battery", () -> new Item(new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> SENSORY_REMEDY = ITEMS.register("sensory_remedy", () -> new Item(new Item.Properties().rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> SMOKED_RICEBALL = ITEMS.register("smoked_riceball", () -> new ModEpicItem(new Item.Properties()));
    public static final RegistryObject<Item> SOAKED_WOOD = ITEMS.register("soaked_wood", () -> new Item(new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> SOAKED_WOODCHIP = ITEMS.register("soaked_woodchip", () -> new Item(new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> STABILIZED_CARBON = ITEMS.register("stabilized_carbon", () -> new Item(new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> STEEL = ITEMS.register("steel", () -> new Item(new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> STEEL_BOTTLE = ITEMS.register("steel_bottle", () -> new Item(new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> STEEL_JAR = ITEMS.register("steel_jar", () -> new Item(new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> STEEL_PART = ITEMS.register("steel_part", () -> new Item(new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> TARTPEPPER = ITEMS.register("tartpepper", () -> new BlockItem(ModBlocks.TARTPEPPER_BLOCK.get(), new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> TARTPEPPER_PICKLE = ITEMS.register("tartpepper_pickle", () -> new Item(new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> TARTPEPPER_SALAD = ITEMS.register("tartpepper_salad", () -> new Item(new Item.Properties().rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> TARTPEPPER_SEED = ITEMS.register("tartpepper_seed", () -> new Item(new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> THORNY_YAZHEN = ITEMS.register("thorny_yazhen", () -> new BlockItem(ModBlocks.THORNY_YAZHEN_BLOCK.get(), new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> THORNY_YAZHEN_POWDER = ITEMS.register("thorny_yazhen_powder", () -> new Item(new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> UMBRALINE = ITEMS.register("umbraline", () -> new BlockItem(ModBlocks.UMBRALINE_BLOCK.get(), new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> VALLEY_GRAYBREAD = ITEMS.register("valley_graybread", () -> new Item(new Item.Properties().rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> WOOD = ITEMS.register("wood", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> WULING_FRIED_RICE = ITEMS.register("wuling_fried_rice", () -> new ModEpicItem(new Item.Properties()));
    public static final RegistryObject<Item> YAZHEN = ITEMS.register("yazhen", () -> new BlockItem(ModBlocks.YAZHEN_BLOCK.get(), new Item.Properties()));
    public static final RegistryObject<Item> YAZHEN_POWDER = ITEMS.register("yazhen_powder", () -> new Item(new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> YAZHEN_SEED = ITEMS.register("yazhen_seed", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> YAZHEN_SPRAY_L = ITEMS.register("yazhen_spray_l", () -> new ModEpicItem(new Item.Properties()));
    public static final RegistryObject<Item> YAZHEN_SPRAY_S = ITEMS.register("yazhen_spray_s", () -> new Item(new Item.Properties().rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> YAZHEN_SYRINGE_A = ITEMS.register("yazhen_syringe_a", () -> new Item(new Item.Properties().rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> YAZHEN_SYRINGE_C = ITEMS.register("yazhen_syringe_c", () -> new Item(new Item.Properties().rarity(Rarity.RARE)));

    public static void register(IEventBus bus) {
        ITEMS.register(bus);
    }
}
